export { Main } from './Main';
export { NotFound } from './NotFound';
export { SignUp } from './SignUp';
export { Catalog } from './Catalog';
export { Cart } from './Cart';
export { About } from './About';
export { Profile } from './Profile';
export { SignIn } from './SignIn';
export { ProductDetail } from './ProductDetail';
